language: go
branches:
  only:
  - master
go:
- '1.6'
env:
  global:
  - GH_REF=github.com/dennisgranath/gocd-plumber
  - secure: J3m1/xVi/K6xWI8xhcwIAuMZ8aUQ+xgMzjwMfPHcxmdtRGaxbEfKTRBaawB1dB+ONNesURTP/CztHLwXWKGHBXbJHQQV3HAyumt1bSsVbe2mTGU/twQVll/lFc2CcWUbn3RIomZ3xp5ctanG74Py1AuvO1OYJ9D60Cc2T1D44+eZw6ccvSUV3AMI8nuutk6F3Z5YIoGGE/yuNuef7m+S476cjW57MLo+iQjXvIGmwFri5tDnZWwcV7Ah9UJdqB/D/9pVw5GyZW898nvqHLydP1iAqJ3AC8MjpOFuQLJweWLrVVoEpnELT5uEvUq8cA803WySrnsOHrrWyzcsFQskd3lc3FU0+2/vLhbC3DrUmkROeBslZg5wBTH9u8WY2USx8tV3OKsjKZYMPADpqBG1s987ZyoXh0q5yEewFnJ6TUuA/OraMSQrxuw+FYfQcTw5fE/tAMZbnJFxt0qWQ0ppQClxt0Bhp6uf+7/k7c9M6z17WGcw/sDb5SWm/kclng3D843Px5GieboMXFZO+5gLBLdpncU0+vvdNr0oXZj/hssSENlzS7t7qZwCyasGUJCoDZmcLM5N9EPmQsy1jtwYjdG8iA3tjBOVxxN3EA2gd9oUWM0g1aPpqEPEBz4g5Zfriokj+baaa9s3TmBvxbXkyc0MQfVHnxXEHiw+6B2ezxk=
before_script: |
  # Get semver version for HEAD if exists
  VERSION=$(git tag --contains HEAD | grep "v[0-9]*\.[0-9]*\.[0-9]*")
  if [ -z "$VERSION" ]; then
    # Increment minor and set patch to 0
    VERSION=$(git describe --tags --match 'v[0-9]*\.[0-9]*\.[0-9]*' | \
      awk -F. '{printf("%s.%s.0", $1, $2+1)}')

    # Set git user config for tag
    git config user.name "dennisgranath"
    git config user.email "dennis@diabol.com"

    # Create new version tag
    git tag -a "$VERSION" -m "Version $VERSION"
    echo "New version $VERSION"
  else
    echo "HEAD already tagged $VERSION"
  fi
script:
- make
before_deploy: |
  # Get semver version for HEAD
  VERSION=$(git tag --contains HEAD | grep "v[0-9]*\.[0-9]*\.[0-9]*")
  # Push tag if not present on origin
  git ls-remote --exit-code origin refs/tags/$VERSION || {
    # Send stdout to dev/null to protect GH_TOKEN
    git push --quiet "https://${GH_TOKEN}@${GH_REF}" --tags > /dev/null 2>&1
  }
deploy:
- provider: releases
  api_key:
    secure: YZyV19RtUmqVSVCNlB1UuH2AAj/TQbtOkgamLul5WNEyPpCCf+45QqPcgja+/NiQI+HMEZaM/nmTGW/vehAtZFeAmRUqnLfehPU7cL43aHMEQoIdiGatLuOY4HJjMHE8/opMFEFW4ttjGXoYWwY7aOXwKsyu4HY81/75/4JvMKKoHjPIf+d8j/hPofB54mIWB80tS1AFE9/wyhbv/Ulj1Tui4xrNmRVQvXDLvOLCZPpBLLIKdmnUp5TgwaOmdZ53WA8PdmIB2i8XatcA/LZQcJW6eS/oZbsr+oXWQ3nYe83m4jJ8tFDFC72pHvfnwcEfBZaK2EgbC8pelkuU0iH5p2TvcVG6fQVrLgBgh2t11vn93xMPtD/dDEso3RiwoCPDK0VICsOBljKWjUYrrIwH8dVb+dnk75/SsUTjFjG/bVMco+ORFNYyWBAzYsG3W5uGNsWUo1J4ZGKk2PJhzU5fOmG5wtq+OKO9RBcShyCViEPEC2JP0rd6qAiDOxh6Iaxv3qDlVDITpOwE2FZcpWDec6GB85YXcaO3h23TCHYU6fRHE34yj0aKsMliEKZ17yMS4XXcVI1rE8FilbnpkohfT7G9XT5tcgbVhjq5mgEwrPFolEfE46C45syHVZuc0tpUnPJlx3ksk8zqfu3Nq4nu0iiAx24crLMpEA2oMoH3I+U=
  file: ARTIFACTS/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: dennisgranath/gocd-plumber
